#!/usr/bin/env bash

ayken_path_contract_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AYKEN_REPO_ROOT="${AYKEN_REPO_ROOT:-$(cd "${ayken_path_contract_dir}/../.." && pwd)}"

AYKEN_OUT_DIR="${AYKEN_OUT_DIR:-${AYKEN_REPO_ROOT}/out}"
AYKEN_BUILD_DIR="${AYKEN_BUILD_DIR:-${AYKEN_OUT_DIR}/build}"
AYKEN_LOG_DIR="${AYKEN_LOG_DIR:-${AYKEN_OUT_DIR}/logs}"
AYKEN_LOCAL_EVIDENCE_DIR="${AYKEN_LOCAL_EVIDENCE_DIR:-${AYKEN_OUT_DIR}/evidence}"
AYKEN_LOCAL_REPORT_DIR="${AYKEN_LOCAL_REPORT_DIR:-${AYKEN_OUT_DIR}/reports}"
CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-${AYKEN_OUT_DIR}/cargo}"
AYKEN_LEGACY_ROOT_ARTIFACTS="${AYKEN_LEGACY_ROOT_ARTIFACTS:-1}"

AYKEN_KERNEL_ELF="${AYKEN_KERNEL_ELF:-${AYKEN_BUILD_DIR}/kernel.elf}"
AYKEN_BOOT_EFI="${AYKEN_BOOT_EFI:-${AYKEN_BUILD_DIR}/BOOTX64.EFI}"
AYKEN_EFI_IMG="${AYKEN_EFI_IMG:-${AYKEN_BUILD_DIR}/EFI.img}"
AYKEN_OVMF_CODE="${AYKEN_OVMF_CODE:-${AYKEN_REPO_ROOT}/firmware/ovmf/OVMF_CODE.fd}"
AYKEN_OVMF_VARS_CLEAN="${AYKEN_OVMF_VARS_CLEAN:-${AYKEN_REPO_ROOT}/OVMF_VARS.clean.fd}"
AYKEN_OVMF_VARS_RUN="${AYKEN_OVMF_VARS_RUN:-${AYKEN_BUILD_DIR}/ovmf_vars.fd}"

ayken_prepare_out_dirs() {
    mkdir -p \
        "${AYKEN_BUILD_DIR}" \
        "${AYKEN_LOG_DIR}" \
        "${AYKEN_LOCAL_EVIDENCE_DIR}" \
        "${AYKEN_LOCAL_REPORT_DIR}" \
        "${CARGO_TARGET_DIR}"
}
