AYKEN_OUT_DIR ?= out
AYKEN_BUILD_DIR ?= $(AYKEN_OUT_DIR)/build
AYKEN_LOG_DIR ?= $(AYKEN_OUT_DIR)/logs
AYKEN_LOCAL_EVIDENCE_DIR ?= $(AYKEN_OUT_DIR)/evidence
AYKEN_LOCAL_REPORT_DIR ?= $(AYKEN_OUT_DIR)/reports
CARGO_TARGET_DIR ?= $(abspath $(AYKEN_OUT_DIR)/cargo)
AYKEN_LEGACY_ROOT_ARTIFACTS ?= 1

KERNEL_ELF ?= $(AYKEN_BUILD_DIR)/kernel.elf
PROFILE_STAMP ?= $(AYKEN_BUILD_DIR)/.build_profile.stamp
BOOT_EFI ?= $(AYKEN_BUILD_DIR)/BOOTX64.EFI
EFI_IMG ?= $(AYKEN_BUILD_DIR)/EFI.img
OVMF_CODE ?= firmware/ovmf/OVMF_CODE.fd
OVMF_VARS_CLEAN ?= OVMF_VARS.clean.fd
OVMF_VARS_RUN ?= $(AYKEN_BUILD_DIR)/ovmf_vars.fd

LEGACY_KERNEL_ELF := $(if $(filter 1,$(AYKEN_LEGACY_ROOT_ARTIFACTS)),kernel.elf,)
LEGACY_BOOT_EFI := $(if $(filter 1,$(AYKEN_LEGACY_ROOT_ARTIFACTS)),bootloader/efi/BOOTX64.EFI,)
LEGACY_EFI_IMG := $(if $(filter 1,$(AYKEN_LEGACY_ROOT_ARTIFACTS)),EFI.img,)

ifeq ($(origin EVIDENCE_ROOT), undefined)
ifneq ($(strip $(CI)),)
EVIDENCE_ROOT := evidence
else
EVIDENCE_ROOT := $(AYKEN_LOCAL_EVIDENCE_DIR)
endif
endif

export AYKEN_OUT_DIR
export AYKEN_BUILD_DIR
export AYKEN_LOG_DIR
export AYKEN_LOCAL_EVIDENCE_DIR
export AYKEN_LOCAL_REPORT_DIR
export CARGO_TARGET_DIR
export AYKEN_LEGACY_ROOT_ARTIFACTS
