//! Debug Operations Implementation
//!
//! This module implements debug operations using sequence references (AR-3).
//! Debug operations provide introspection and analysis capabilities without side effects.
//!
//! # Phase 3.5.1.a Scope
//! - Explain command using sequence ID references
//! - Dry-run mode using sequence ID references  
//! - Command history
//!
//! # AR-3 Compliance
//! Debug instructions use sequence ID references instead of recursive BCIB structures.
//! This enables history/replay/audit systems and prevents infinite recursion.

use crate::bcib::{BCIBInstruction, BCIBSequenceRegistry, DebugInstruction};
use crate::error::{ErrorCode, Result, SemanticCLIError};
use crate::operations::{OperationExecutor, OperationResult};
use serde_json::{json, Value as JsonValue};
use std::collections::HashMap;
use std::sync::{Arc, Mutex};
use std::time::Instant;

/// Debug executor for BCIB-based debug operations
///
/// **CRITICAL:** This executor ONLY consumes BCIB instructions from Transformer.
/// It uses sequence ID references (AR-3) to avoid recursive BCIB structures.
pub struct DebugExecutor {
    /// Sequence registry for resolving sequence ID references (AR-3)
    sequence_registry: Arc<Mutex<BCIBSequenceRegistry>>,
    /// Command history for history operations
    command_history: Vec<HistoryEntry>,
}

/// Debug operation input - BCIB sequence from Transformer
#[derive(Debug, Clone)]
pub struct DebugInput {
    /// BCIB instructions from Transformer (NOT generated by executor)
    pub instructions: Vec<BCIBInstruction>,
}

/// Debug operation result
#[derive(Debug, Clone)]
pub struct DebugResult {
    pub operation_type: String,
    pub data: JsonValue,
    pub execution_time_ms: u64,
    pub success: bool,
    pub error_message: Option<String>,
}

/// History entry for command tracking
#[derive(Debug, Clone)]
struct HistoryEntry {
    pub sequence_id: String,
    pub command: String,
    pub timestamp: chrono::DateTime<chrono::Utc>,
    pub success: bool,
    pub execution_time_ms: u64,
}

impl DebugExecutor {
    /// Create new debug executor
    pub fn new() -> Self {
        Self {
            sequence_registry: Arc::new(Mutex::new(BCIBSequenceRegistry::new())),
            command_history: Vec::new(),
        }
    }

    /// Create debug executor with existing sequence registry (for integration)
    pub fn with_registry(registry: Arc<Mutex<BCIBSequenceRegistry>>) -> Self {
        Self {
            sequence_registry: registry,
            command_history: Vec::new(),
        }
    }

    /// Add command to history
    pub fn add_to_history(
        &mut self,
        sequence_id: String,
        command: String,
        success: bool,
        execution_time_ms: u64,
    ) {
        let entry = HistoryEntry {
            sequence_id,
            command,
            timestamp: chrono::Utc::now(),
            success,
            execution_time_ms,
        };
        self.command_history.push(entry);

        // Keep only last 100 entries to prevent unbounded growth
        if self.command_history.len() > 100 {
            self.command_history.remove(0);
        }
    }

    /// Execute explain operation using sequence ID reference (AR-3)
    fn execute_explain(&self, target_sequence_id: &str) -> Result<JsonValue> {
        let registry = self.sequence_registry.lock().map_err(|_| {
            SemanticCLIError::execution_error(
                "Failed to acquire sequence registry lock",
                ErrorCode::E500,
            )
        })?;

        let sequence = registry.get(target_sequence_id).ok_or_else(|| {
            SemanticCLIError::validation_error(
                format!("Sequence ID '{}' not found in registry", target_sequence_id),
                "Provide a valid sequence ID from a previous command",
                ErrorCode::E500,
            )
        })?;

        // Format sequence explanation
        let mut explanations = Vec::new();
        for (i, instruction) in sequence.instructions.iter().enumerate() {
            let explanation = self.explain_instruction(instruction, i + 1);
            explanations.push(explanation);
        }

        Ok(json!({
            "sequence_id": target_sequence_id,
            "instruction_count": sequence.instructions.len(),
            "determinism_level": sequence.metadata.determinism,
            "explanations": explanations,
            "metadata": {
                "created_at": sequence.metadata.created_at,
                "phase": sequence.metadata.phase
            }
        }))
    }

    /// Execute dry-run operation using sequence ID reference (AR-3)
    fn execute_dry_run(&self, target_sequence_id: &str) -> Result<JsonValue> {
        let registry = self.sequence_registry.lock().map_err(|_| {
            SemanticCLIError::execution_error(
                "Failed to acquire sequence registry lock",
                ErrorCode::E500,
            )
        })?;

        let sequence = registry.get(target_sequence_id).ok_or_else(|| {
            SemanticCLIError::validation_error(
                format!("Sequence ID '{}' not found in registry", target_sequence_id),
                "Provide a valid sequence ID from a previous command",
                ErrorCode::E500,
            )
        })?;

        // Simulate execution without side effects
        let mut simulation_steps = Vec::new();
        let mut simulated_state = HashMap::new();

        for (i, instruction) in sequence.instructions.iter().enumerate() {
            let step = self.simulate_instruction(instruction, i + 1, &mut simulated_state)?;
            simulation_steps.push(step);
        }

        Ok(json!({
            "sequence_id": target_sequence_id,
            "simulation_steps": simulation_steps,
            "final_state": simulated_state,
            "would_succeed": true,
            "side_effects": "none (dry-run mode)",
            "metadata": {
                "instruction_count": sequence.instructions.len(),
                "determinism_level": sequence.metadata.determinism
            }
        }))
    }

    /// Execute history operation
    fn execute_history(&self) -> Result<JsonValue> {
        let history_data: Vec<JsonValue> = self
            .command_history
            .iter()
            .rev() // Most recent first
            .take(20) // Last 20 commands
            .map(|entry| {
                json!({
                    "sequence_id": entry.sequence_id,
                    "command": entry.command,
                    "timestamp": entry.timestamp.to_rfc3339(),
                    "success": entry.success,
                    "execution_time_ms": entry.execution_time_ms
                })
            })
            .collect();

        Ok(json!({
            "total_commands": self.command_history.len(),
            "showing_recent": history_data.len(),
            "history": history_data
        }))
    }

    /// Explain a single instruction
    fn explain_instruction(&self, instruction: &BCIBInstruction, step: usize) -> JsonValue {
        match instruction {
            BCIBInstruction::Context(ctx_inst) => match ctx_inst {
                crate::bcib::ContextInstruction::LoadContext { path, .. } => {
                    json!({
                        "step": step,
                        "type": "Context",
                        "operation": "LoadContext",
                        "description": format!("Load context data from '{}'", path),
                        "details": {
                            "context_path": path,
                            "capability_required": format!("Read{{context: \"{}\"}}", path)
                        }
                    })
                }
                crate::bcib::ContextInstruction::Return { .. } => {
                    json!({
                        "step": step,
                        "type": "Context",
                        "operation": "Return",
                        "description": "Return the current result to caller",
                        "details": {
                            "side_effects": "none"
                        }
                    })
                }
            },
            BCIBInstruction::Query(query_inst) => match query_inst {
                crate::bcib::QueryInstruction::ApplyFilter { expression, .. } => {
                    json!({
                        "step": step,
                        "type": "Query",
                        "operation": "ApplyFilter",
                        "description": format!("Filter items where {} {:?} value", expression.field, expression.operator),
                        "details": {
                            "field": expression.field,
                            "operator": format!("{:?}", expression.operator),
                            "normalized": expression.normalized
                        }
                    })
                }
                crate::bcib::QueryInstruction::ApplyFilterBool {
                    filter_register, ..
                } => {
                    json!({
                        "step": step,
                        "type": "Query",
                        "operation": "ApplyFilterBool",
                        "description": format!("Apply boolean filter from register {}", filter_register),
                        "details": {
                            "filter_register": filter_register
                        }
                    })
                }
                crate::bcib::QueryInstruction::LoadField {
                    field,
                    target_register,
                    ..
                } => {
                    json!({
                        "step": step,
                        "type": "Query",
                        "operation": "LoadField",
                        "description": format!("Load field '{}' into register {}", field, target_register),
                        "details": {
                            "field": field,
                            "target_register": target_register
                        }
                    })
                }
                crate::bcib::QueryInstruction::LoadLiteral {
                    value,
                    target_register,
                    ..
                } => {
                    json!({
                        "step": step,
                        "type": "Query",
                        "operation": "LoadLiteral",
                        "description": format!("Load literal value into register {}", target_register),
                        "details": {
                            "value": format!("{:?}", value),
                            "target_register": target_register
                        }
                    })
                }
                crate::bcib::QueryInstruction::Compare {
                    left,
                    operator,
                    right,
                    target_register,
                    ..
                } => {
                    json!({
                        "step": step,
                        "type": "Query",
                        "operation": "Compare",
                        "description": format!("Compare operands using {:?} operator", operator),
                        "details": {
                            "left_operand": format!("{:?}", left),
                            "operator": format!("{:?}", operator),
                            "right_operand": format!("{:?}", right),
                            "target_register": target_register
                        }
                    })
                }
                crate::bcib::QueryInstruction::LogicalOp {
                    operator,
                    operands,
                    target_register,
                    ..
                } => {
                    json!({
                        "step": step,
                        "type": "Query",
                        "operation": "LogicalOp",
                        "description": format!("Apply {:?} logical operation", operator),
                        "details": {
                            "operator": format!("{:?}", operator),
                            "operand_count": operands.len(),
                            "target_register": target_register
                        }
                    })
                }
            },
            BCIBInstruction::System(sys_inst) => match sys_inst {
                crate::bcib::SystemInstruction::SystemStatus { .. } => {
                    json!({
                        "step": step,
                        "type": "System",
                        "operation": "SystemStatus",
                        "description": "Query system status and health metrics",
                        "details": {
                            "capability_required": "System{scope: \"status\"}"
                        }
                    })
                }
                crate::bcib::SystemInstruction::ListAgents { .. } => {
                    json!({
                        "step": step,
                        "type": "System",
                        "operation": "ListAgents",
                        "description": "List active agents and their status",
                        "details": {
                            "capability_required": "System{scope: \"agents\"}"
                        }
                    })
                }
            },
            BCIBInstruction::Debug(debug_inst) => match debug_inst {
                DebugInstruction::Explain {
                    target_sequence_id, ..
                } => {
                    json!({
                        "step": step,
                        "type": "Debug",
                        "operation": "Explain",
                        "description": format!("Explain sequence '{}'", target_sequence_id),
                        "details": {
                            "target_sequence_id": target_sequence_id,
                            "capability_required": "Debug"
                        }
                    })
                }
                DebugInstruction::DryRun {
                    target_sequence_id, ..
                } => {
                    json!({
                        "step": step,
                        "type": "Debug",
                        "operation": "DryRun",
                        "description": format!("Simulate sequence '{}'", target_sequence_id),
                        "details": {
                            "target_sequence_id": target_sequence_id,
                            "capability_required": "Debug"
                        }
                    })
                }
                DebugInstruction::History { .. } => {
                    json!({
                        "step": step,
                        "type": "Debug",
                        "operation": "History",
                        "description": "Show command execution history",
                        "details": {
                            "capability_required": "Debug"
                        }
                    })
                }
            },
            BCIBInstruction::Loop(_) => {
                json!({
                    "step": step,
                    "type": "Loop",
                    "operation": "NotImplemented",
                    "description": "Loop instructions not yet implemented in Phase 1",
                    "details": {
                        "status": "Phase 1 - Skeletal implementation only"
                    }
                })
            }
            BCIBInstruction::ControlFlow(_) => {
                json!({
                    "step": step,
                    "type": "ControlFlow",
                    "operation": "NotImplemented",
                    "description": "Control flow instructions not yet implemented in Phase 2.3",
                    "details": {
                        "status": "Phase 2.3 - Implementation in progress"
                    }
                })
            }
        }
    }

    /// Simulate instruction execution without side effects
    fn simulate_instruction(
        &self,
        instruction: &BCIBInstruction,
        step: usize,
        state: &mut HashMap<String, JsonValue>,
    ) -> Result<JsonValue> {
        match instruction {
            BCIBInstruction::Context(ctx_inst) => match ctx_inst {
                crate::bcib::ContextInstruction::LoadContext { path, .. } => {
                    state.insert("current_context".to_string(), json!(path));
                    Ok(json!({
                        "step": step,
                        "action": "load_context",
                        "result": format!("Context '{}' would be loaded", path),
                        "state_change": format!("current_context = '{}'", path)
                    }))
                }
                crate::bcib::ContextInstruction::Return { .. } => Ok(json!({
                    "step": step,
                    "action": "return",
                    "result": "Current result would be returned",
                    "state_change": "none"
                })),
            },
            BCIBInstruction::Query(query_inst) => match query_inst {
                crate::bcib::QueryInstruction::ApplyFilter { expression, .. } => {
                    state.insert("filtered_items".to_string(), json!("filtered_result"));
                    Ok(json!({
                        "step": step,
                        "action": "apply_filter",
                        "result": format!("Items would be filtered by {}", expression.field),
                        "state_change": "filtered_items = filtered_result"
                    }))
                }
                crate::bcib::QueryInstruction::ApplyFilterBool {
                    filter_register, ..
                } => {
                    state.insert(
                        "filtered_items".to_string(),
                        json!("boolean_filtered_result"),
                    );
                    Ok(json!({
                        "step": step,
                        "action": "apply_filter_bool",
                        "result": format!("Items would be filtered by boolean register {}", filter_register),
                        "state_change": "filtered_items = boolean_filtered_result"
                    }))
                }
                crate::bcib::QueryInstruction::LoadField {
                    field,
                    target_register,
                    ..
                } => {
                    let register_key = format!("register_{}", target_register);
                    state.insert(register_key.clone(), json!(format!("field_{}", field)));
                    Ok(json!({
                        "step": step,
                        "action": "load_field",
                        "result": format!("Field '{}' would be loaded", field),
                        "state_change": format!("{} = field_{}", register_key, field)
                    }))
                }
                crate::bcib::QueryInstruction::LoadLiteral {
                    value,
                    target_register,
                    ..
                } => {
                    let register_key = format!("register_{}", target_register);
                    state.insert(register_key.clone(), json!(format!("{:?}", value)));
                    Ok(json!({
                        "step": step,
                        "action": "load_literal",
                        "result": format!("Literal {:?} would be loaded", value),
                        "state_change": format!("{} = {:?}", register_key, value)
                    }))
                }
                crate::bcib::QueryInstruction::Compare {
                    target_register, ..
                } => {
                    let register_key = format!("register_{}", target_register);
                    state.insert(register_key.clone(), json!(true));
                    Ok(json!({
                        "step": step,
                        "action": "compare",
                        "result": "Comparison would be performed",
                        "state_change": format!("{} = comparison_result", register_key)
                    }))
                }
                crate::bcib::QueryInstruction::LogicalOp {
                    target_register, ..
                } => {
                    let register_key = format!("register_{}", target_register);
                    state.insert(register_key.clone(), json!(true));
                    Ok(json!({
                        "step": step,
                        "action": "logical_op",
                        "result": "Logical operation would be performed",
                        "state_change": format!("{} = logical_result", register_key)
                    }))
                }
            },
            BCIBInstruction::System(sys_inst) => match sys_inst {
                crate::bcib::SystemInstruction::SystemStatus { .. } => {
                    state.insert("system_status".to_string(), json!("healthy"));
                    Ok(json!({
                        "step": step,
                        "action": "system_status",
                        "result": "System status would be queried",
                        "state_change": "system_status = healthy"
                    }))
                }
                crate::bcib::SystemInstruction::ListAgents { .. } => {
                    state.insert("agents".to_string(), json!(["agent1", "agent2"]));
                    Ok(json!({
                        "step": step,
                        "action": "list_agents",
                        "result": "Active agents would be listed",
                        "state_change": "agents = [agent1, agent2]"
                    }))
                }
            },
            BCIBInstruction::Debug(_) => Ok(json!({
                "step": step,
                "action": "debug_operation",
                "result": "Debug operation would be performed",
                "state_change": "none (debug operations don't modify state)"
            })),
            BCIBInstruction::Loop(_) => Ok(json!({
                "step": step,
                "action": "loop_operation",
                "result": "Loop operation not yet implemented in Phase 1",
                "state_change": "none (skeletal implementation)"
            })),
            BCIBInstruction::ControlFlow(_) => Ok(json!({
                "step": step,
                "action": "control_flow_operation",
                "result": "Control flow operation not yet implemented in Phase 2.3",
                "state_change": "none (implementation in progress)"
            })),
        }
    }
}

impl OperationExecutor for DebugExecutor {
    type Input = DebugInput;
    type Output = DebugResult;
    type Error = SemanticCLIError;

    fn execute(&self, input: Self::Input) -> Result<Self::Output> {
        let start_time = Instant::now();

        // Validate input
        if input.instructions.is_empty() {
            return Err(SemanticCLIError::validation_error(
                "Debug operation requires at least one instruction",
                "Provide a valid BCIB sequence",
                ErrorCode::E400,
            ));
        }

        let mut operation_type = String::new();
        let mut result_data = json!(null);

        // Process debug instructions
        for instruction in &input.instructions {
            match instruction {
                BCIBInstruction::Debug(debug_inst) => match debug_inst {
                    DebugInstruction::Explain {
                        target_sequence_id, ..
                    } => {
                        if !operation_type.is_empty() {
                            return Err(SemanticCLIError::validation_error(
                                "Multiple debug operations in single sequence not allowed",
                                "Use exactly one Debug instruction",
                                ErrorCode::E400,
                            ));
                        }
                        operation_type = "explain".to_string();
                        result_data = self.execute_explain(target_sequence_id)?;
                    }
                    DebugInstruction::DryRun {
                        target_sequence_id, ..
                    } => {
                        if !operation_type.is_empty() {
                            return Err(SemanticCLIError::validation_error(
                                "Multiple debug operations in single sequence not allowed",
                                "Use exactly one Debug instruction",
                                ErrorCode::E400,
                            ));
                        }
                        operation_type = "dry_run".to_string();
                        result_data = self.execute_dry_run(target_sequence_id)?;
                    }
                    DebugInstruction::History { .. } => {
                        if !operation_type.is_empty() {
                            return Err(SemanticCLIError::validation_error(
                                "Multiple debug operations in single sequence not allowed",
                                "Use exactly one Debug instruction",
                                ErrorCode::E400,
                            ));
                        }
                        operation_type = "history".to_string();
                        result_data = self.execute_history()?;
                    }
                },
                BCIBInstruction::Context(crate::bcib::ContextInstruction::Return { .. }) => {
                    // Return instruction is allowed in debug operations
                    continue;
                }
                _ => {
                    return Err(SemanticCLIError::validation_error(
                        format!(
                            "Instruction type not supported in debug operations: {:?}",
                            instruction
                        ),
                        "Debug operations only support Debug and Return instructions",
                        ErrorCode::E400,
                    ));
                }
            }
        }

        // Validate that we found a debug operation
        if operation_type.is_empty() {
            return Err(SemanticCLIError::validation_error(
                "No debug operation found in BCIB sequence",
                "Provide a Debug instruction (Explain, DryRun, or History)",
                ErrorCode::E400,
            ));
        }

        let execution_time = start_time.elapsed().as_millis() as u64;

        Ok(DebugResult {
            operation_type,
            data: result_data,
            execution_time_ms: execution_time,
            success: true,
            error_message: None,
        })
    }
}

impl OperationResult for DebugResult {
    fn format(&self) -> String {
        match self.operation_type.as_str() {
            "explain" => {
                if let Some(explanations) = self.data.get("explanations").and_then(|e| e.as_array())
                {
                    let mut output = format!("=== Sequence Explanation ===\n");
                    output.push_str(&format!(
                        "Sequence ID: {}\n",
                        self.data
                            .get("sequence_id")
                            .and_then(|s| s.as_str())
                            .unwrap_or("unknown")
                    ));
                    output.push_str(&format!(
                        "Instructions: {}\n\n",
                        self.data
                            .get("instruction_count")
                            .and_then(|c| c.as_u64())
                            .unwrap_or(0)
                    ));

                    for explanation in explanations {
                        if let (Some(step), Some(op), Some(desc)) = (
                            explanation.get("step").and_then(|s| s.as_u64()),
                            explanation.get("operation").and_then(|o| o.as_str()),
                            explanation.get("description").and_then(|d| d.as_str()),
                        ) {
                            output.push_str(&format!("{}. {} - {}\n", step, op, desc));
                        }
                    }
                    output
                } else {
                    "Explanation data not available".to_string()
                }
            }
            "dry_run" => {
                if let Some(steps) = self.data.get("simulation_steps").and_then(|s| s.as_array()) {
                    let mut output = format!("=== Dry Run Simulation ===\n");
                    output.push_str(&format!(
                        "Sequence ID: {}\n",
                        self.data
                            .get("sequence_id")
                            .and_then(|s| s.as_str())
                            .unwrap_or("unknown")
                    ));
                    output.push_str(&format!("Steps: {}\n\n", steps.len()));

                    for step in steps {
                        if let (Some(step_num), Some(action), Some(result)) = (
                            step.get("step").and_then(|s| s.as_u64()),
                            step.get("action").and_then(|a| a.as_str()),
                            step.get("result").and_then(|r| r.as_str()),
                        ) {
                            output.push_str(&format!("{}. {} → {}\n", step_num, action, result));
                        }
                    }
                    output.push_str("\n✓ Simulation completed successfully (no side effects)\n");
                    output
                } else {
                    "Dry run data not available".to_string()
                }
            }
            "history" => {
                if let Some(history) = self.data.get("history").and_then(|h| h.as_array()) {
                    let mut output = format!("=== Command History ===\n");
                    output.push_str(&format!(
                        "Total commands: {}\n",
                        self.data
                            .get("total_commands")
                            .and_then(|c| c.as_u64())
                            .unwrap_or(0)
                    ));
                    output.push_str(&format!("Showing recent: {}\n\n", history.len()));

                    for entry in history {
                        if let (Some(cmd), Some(timestamp), Some(success)) = (
                            entry.get("command").and_then(|c| c.as_str()),
                            entry.get("timestamp").and_then(|t| t.as_str()),
                            entry.get("success").and_then(|s| s.as_bool()),
                        ) {
                            let status = if success { "✓" } else { "✗" };
                            output.push_str(&format!("{} {} ({})\n", status, cmd, timestamp));
                        }
                    }
                    output
                } else {
                    "History data not available".to_string()
                }
            }
            _ => format!(
                "Debug operation '{}' completed in {}ms",
                self.operation_type, self.execution_time_ms
            ),
        }
    }

    fn metadata(&self) -> HashMap<String, serde_json::Value> {
        let mut metadata = HashMap::new();
        metadata.insert("operation_type".to_string(), json!(self.operation_type));
        metadata.insert(
            "execution_time_ms".to_string(),
            json!(self.execution_time_ms),
        );
        metadata.insert("success".to_string(), json!(self.success));

        if let Some(error) = &self.error_message {
            metadata.insert("error_message".to_string(), json!(error));
        }

        metadata
    }

    fn is_success(&self) -> bool {
        self.success
    }
}

impl Default for DebugExecutor {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::bcib::DeterminismLevel;
    use crate::types::SourceLocation;

    fn test_location() -> SourceLocation {
        SourceLocation::new(1, 1, 0)
    }

    fn create_test_sequence() -> crate::bcib::BCIBSequence {
        crate::bcib::BCIBSequence {
            instructions: vec![
                BCIBInstruction::Context(crate::bcib::ContextInstruction::LoadContext {
                    path: "data.users".to_string(),
                    location: test_location(),
                }),
                BCIBInstruction::Context(crate::bcib::ContextInstruction::Return {
                    location: test_location(),
                }),
            ],
            metadata: crate::bcib::BCIBMetadata {
                sequence_id: "test-sequence-123".to_string(),
                determinism: DeterminismLevel::Deterministic,
                created_at: 1642262400, // Fixed timestamp for testing
                phase: "3.5.1".to_string(),
            },
        }
    }

    #[test]
    fn test_debug_executor_creation() {
        let executor = DebugExecutor::new();
        assert_eq!(executor.command_history.len(), 0);
    }

    #[test]
    fn test_explain_operation() {
        let registry = Arc::new(Mutex::new(BCIBSequenceRegistry::new()));
        let sequence = create_test_sequence();
        let sequence_id = sequence.metadata.sequence_id.clone();

        // Register sequence
        {
            let mut reg = registry.lock().unwrap();
            reg.register(sequence);
        }

        let executor = DebugExecutor::with_registry(registry);

        let input = DebugInput {
            instructions: vec![
                BCIBInstruction::Debug(DebugInstruction::Explain {
                    target_sequence_id: sequence_id,
                    location: test_location(),
                }),
                BCIBInstruction::Context(crate::bcib::ContextInstruction::Return {
                    location: test_location(),
                }),
            ],
        };

        let result = executor.execute(input).unwrap();
        assert!(result.is_success());
        assert_eq!(result.operation_type, "explain");
        assert!(result.data.get("explanations").is_some());
    }

    #[test]
    fn test_dry_run_operation() {
        let registry = Arc::new(Mutex::new(BCIBSequenceRegistry::new()));
        let sequence = create_test_sequence();
        let sequence_id = sequence.metadata.sequence_id.clone();

        // Register sequence
        {
            let mut reg = registry.lock().unwrap();
            reg.register(sequence);
        }

        let executor = DebugExecutor::with_registry(registry);

        let input = DebugInput {
            instructions: vec![
                BCIBInstruction::Debug(DebugInstruction::DryRun {
                    target_sequence_id: sequence_id,
                    location: test_location(),
                }),
                BCIBInstruction::Context(crate::bcib::ContextInstruction::Return {
                    location: test_location(),
                }),
            ],
        };

        let result = executor.execute(input).unwrap();
        assert!(result.is_success());
        assert_eq!(result.operation_type, "dry_run");
        assert!(result.data.get("simulation_steps").is_some());
    }

    #[test]
    fn test_history_operation() {
        let mut executor = DebugExecutor::new();

        // Add some history entries
        executor.add_to_history("seq1".to_string(), "list users".to_string(), true, 50);
        executor.add_to_history("seq2".to_string(), "show user 123".to_string(), true, 75);

        let input = DebugInput {
            instructions: vec![
                BCIBInstruction::Debug(DebugInstruction::History {
                    location: test_location(),
                }),
                BCIBInstruction::Context(crate::bcib::ContextInstruction::Return {
                    location: test_location(),
                }),
            ],
        };

        let result = executor.execute(input).unwrap();
        assert!(result.is_success());
        assert_eq!(result.operation_type, "history");
        assert_eq!(
            result.data.get("total_commands").unwrap().as_u64().unwrap(),
            2
        );
    }

    #[test]
    fn test_sequence_not_found() {
        let executor = DebugExecutor::new();

        let input = DebugInput {
            instructions: vec![BCIBInstruction::Debug(DebugInstruction::Explain {
                target_sequence_id: "nonexistent".to_string(),
                location: test_location(),
            })],
        };

        let result = executor.execute(input);
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("not found"));
    }

    #[test]
    fn test_multiple_debug_operations_rejected() {
        let executor = DebugExecutor::new();

        let input = DebugInput {
            instructions: vec![
                BCIBInstruction::Debug(DebugInstruction::History {
                    location: test_location(),
                }),
                BCIBInstruction::Debug(DebugInstruction::Explain {
                    target_sequence_id: "test".to_string(),
                    location: test_location(),
                }),
            ],
        };

        let result = executor.execute(input);
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .to_string()
            .contains("Multiple debug operations"));
    }

    #[test]
    fn test_empty_sequence_rejected() {
        let executor = DebugExecutor::new();

        let input = DebugInput {
            instructions: vec![],
        };

        let result = executor.execute(input);
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .to_string()
            .contains("at least one instruction"));
    }

    #[test]
    fn test_unsupported_instruction_rejected() {
        let executor = DebugExecutor::new();

        let input = DebugInput {
            instructions: vec![BCIBInstruction::System(
                crate::bcib::SystemInstruction::SystemStatus {
                    location: test_location(),
                },
            )],
        };

        let result = executor.execute(input);
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .to_string()
            .contains("not supported in debug operations"));
    }

    #[test]
    fn test_no_debug_operation_rejected() {
        let executor = DebugExecutor::new();

        let input = DebugInput {
            instructions: vec![BCIBInstruction::Context(
                crate::bcib::ContextInstruction::Return {
                    location: test_location(),
                },
            )],
        };

        let result = executor.execute(input);
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .to_string()
            .contains("No debug operation found"));
    }

    #[test]
    fn test_result_formatting() {
        let result = DebugResult {
            operation_type: "history".to_string(),
            data: json!({
                "total_commands": 2,
                "history": [
                    {
                        "command": "list users",
                        "timestamp": "2026-01-15T10:00:00Z",
                        "success": true
                    }
                ]
            }),
            execution_time_ms: 25,
            success: true,
            error_message: None,
        };

        let formatted = result.format();
        assert!(formatted.contains("Command History"));
        assert!(formatted.contains("Total commands: 2"));
        assert!(formatted.contains("list users"));
    }

    #[test]
    fn test_history_size_limit() {
        let mut executor = DebugExecutor::new();

        // Add more than 100 entries
        for i in 0..150 {
            executor.add_to_history(format!("seq{}", i), format!("command {}", i), true, 10);
        }

        // Should keep only last 100
        assert_eq!(executor.command_history.len(), 100);

        // Should have the most recent entries
        assert_eq!(
            executor.command_history.last().unwrap().sequence_id,
            "seq149"
        );
        assert_eq!(
            executor.command_history.first().unwrap().sequence_id,
            "seq50"
        );
    }
}
