//! System Operations Implementation
//!
//! This module implements system operations (status, agents) using BCIB instructions.
//! Execution layer ONLY consumes BCIB, never produces it.
//!
//! # Phase 3.5.1.a Scope
//! - System status query with System{scope: "status"}
//! - Agent list query with System{scope: "agents"}
//! - NO orchestration (Phase 3.5.1.b)

use crate::bcib::{BCIBInstruction, ContextInstruction, SystemInstruction};
use crate::context::ContextManager;
use crate::error::{ErrorCode, Result, SemanticCLIError};
use crate::operations::{OperationExecutor, OperationResult};
use serde_json::{json, Value as JsonValue};
use std::collections::HashMap;
use std::time::Instant;

/// System executor for BCIB-based system operations
///
/// **CRITICAL:** This executor ONLY consumes BCIB instructions from Transformer.
/// It does NOT generate BCIB instructions - that's Transformer's job.
pub struct SystemExecutor {
    context_manager: ContextManager,
}

/// System operation input - BCIB sequence from Transformer
#[derive(Debug, Clone)]
pub struct SystemInput {
    /// BCIB instructions from Transformer (NOT generated by executor)
    pub instructions: Vec<BCIBInstruction>,
}

/// System operation result
#[derive(Debug, Clone)]
pub struct SystemResult {
    pub operation_type: String,
    pub data: JsonValue,
    pub execution_time_ms: u64,
    pub success: bool,
    pub error_message: Option<String>,
}

impl SystemExecutor {
    /// Create new system executor
    pub fn new() -> Self {
        Self {
            context_manager: ContextManager::new(),
        }
    }

    /// Create system executor with custom context manager
    pub fn with_context_manager(context_manager: ContextManager) -> Self {
        Self { context_manager }
    }

    /// Execute BCIB sequence from Transformer
    ///
    /// **GATE B COMPLIANCE:** Only consumes BCIB, never generates it
    pub fn execute_bcib_sequence(&mut self, input: SystemInput) -> Result<SystemResult> {
        let start_time = Instant::now();

        // Validate input
        if input.instructions.is_empty() {
            return Err(SemanticCLIError::validation_error(
                "No BCIB instructions provided",
                "Provide a valid BCIB sequence from Transformer",
                ErrorCode::E400,
            ));
        }

        let mut operation_type = String::new();
        let mut result_data = JsonValue::Null;

        // Execute BCIB instruction sequence
        for instruction in &input.instructions {
            match instruction {
                BCIBInstruction::System(sys_inst) => {
                    // **GATE B FIX:** Reject multiple system operations in single sequence
                    if !operation_type.is_empty() {
                        return Err(SemanticCLIError::validation_error(
                            "Multiple system operations in single sequence not allowed",
                            "Use exactly one System instruction",
                            ErrorCode::E400,
                        ));
                    }

                    match sys_inst {
                        SystemInstruction::SystemStatus { .. } => {
                            operation_type = "status".to_string();
                            result_data = self.get_system_status()?;
                        }
                        SystemInstruction::ListAgents { .. } => {
                            operation_type = "agents".to_string();
                            result_data = self.get_agent_list()?;
                        }
                    }
                }
                BCIBInstruction::Context(ctx_inst) => {
                    match ctx_inst {
                        ContextInstruction::Return { .. } => {
                            // Return instruction - finalize result
                            break;
                        }
                        _ => {
                            return Err(SemanticCLIError::execution_error(
                                "Context instructions other than Return not supported in system operations",
                                ErrorCode::E501,
                            ));
                        }
                    }
                }
                BCIBInstruction::Query(_) => {
                    return Err(SemanticCLIError::execution_error(
                        "Query instructions not supported in system operations",
                        ErrorCode::E501,
                    ));
                }
                BCIBInstruction::Debug(_) => {
                    return Err(SemanticCLIError::execution_error(
                        "Debug instructions not supported in system operations",
                        ErrorCode::E501,
                    ));
                }
                BCIBInstruction::Loop(_) => {
                    return Err(SemanticCLIError::execution_error(
                        "Loop instructions not yet implemented in Phase 1",
                        ErrorCode::E501,
                    ));
                }
                BCIBInstruction::ControlFlow(_) => {
                    return Err(SemanticCLIError::execution_error(
                        "Control flow instructions not supported in system operations",
                        ErrorCode::E501,
                    ));
                }
            }
        }

        // **GATE B FIX:** Validate that we found a system operation
        if operation_type.is_empty() {
            return Err(SemanticCLIError::validation_error(
                "No system operation found in BCIB sequence",
                "Provide a System instruction before Return",
                ErrorCode::E400,
            ));
        }

        let execution_time_ms = start_time.elapsed().as_millis() as u64;

        Ok(SystemResult {
            operation_type,
            data: result_data,
            execution_time_ms,
            success: true,
            error_message: None,
        })
    }

    /// Get system status information
    ///
    /// **AR-4 COMPLIANCE:** Uses System{scope: "status"} capability
    fn get_system_status(&self) -> Result<JsonValue> {
        // Simulate system status collection
        // In a real implementation, this would gather actual system metrics

        let status = json!({
            "system": {
                "uptime_seconds": 3600,
                "memory_usage": {
                    "total_mb": 8192,
                    "used_mb": 4096,
                    "available_mb": 4096
                },
                "cpu_usage": {
                    "cores": 8,
                    "load_average": [0.5, 0.7, 0.8],
                    "usage_percent": 25.5
                }
            },
            "semantic_cli": {
                "version": "0.1.0",
                "phase": "3.5.1.a",
                "gate": "B",
                "status": "operational"
            },
            "context_manager": {
                "contexts_loaded": self.context_manager.list_contexts().len(),
                // TODO(Gate C): expose real cache metrics instead of mock
                "cache_hit_rate": 0.85,
                "total_requests": 150
            },
            "timestamp": chrono::Utc::now().to_rfc3339()
        });

        Ok(status)
    }

    /// Get active agent list
    ///
    /// **AR-4 COMPLIANCE:** Uses Read{context: "system.agents"} capability for context access
    fn get_agent_list(&mut self) -> Result<JsonValue> {
        // Load agent information from system.agents context
        // Use Read capability for context access (not System capability)

        let capability = crate::bcib::Capability::Read {
            context: "system.agents".to_string(),
        };

        let agents_data = self
            .context_manager
            .load_context("system.agents", &capability)?;

        // Format agent data for system operation result
        let agents = json!({
            "agents": agents_data,
            "total_count": agents_data.len(),
            "active_count": agents_data.iter()
                .filter(|agent| agent.get("status").and_then(|s| s.as_str()) == Some("active"))
                .count(),
            "timestamp": chrono::Utc::now().to_rfc3339()
        });

        Ok(agents)
    }

    /// Get context manager reference
    pub fn context_manager(&self) -> &ContextManager {
        &self.context_manager
    }
}

impl Default for SystemExecutor {
    fn default() -> Self {
        Self::new()
    }
}

impl OperationExecutor for SystemExecutor {
    type Input = SystemInput;
    type Output = SystemResult;
    type Error = SemanticCLIError;

    fn execute(&self, _input: Self::Input) -> Result<Self::Output> {
        // Note: This requires &mut self, but trait requires &self
        // In practice, this will be called through execute_bcib_sequence
        Err(SemanticCLIError::execution_error(
            "Use execute_bcib_sequence for mutable execution",
            ErrorCode::E501,
        ))
    }
}

impl OperationResult for SystemResult {
    fn format(&self) -> String {
        if !self.success {
            if let Some(ref error) = self.error_message {
                return format!("Error: {}", error);
            }
        }

        match self.operation_type.as_str() {
            "status" => self.format_system_status(),
            "agents" => self.format_agent_list(),
            _ => format!("Unknown system operation: {}", self.operation_type),
        }
    }

    fn metadata(&self) -> HashMap<String, JsonValue> {
        let mut metadata = HashMap::new();
        metadata.insert("operation_type".to_string(), json!(self.operation_type));
        metadata.insert(
            "execution_time_ms".to_string(),
            json!(self.execution_time_ms),
        );
        metadata.insert("success".to_string(), json!(self.success));
        if let Some(ref error) = self.error_message {
            metadata.insert("error_message".to_string(), json!(error));
        }
        metadata
    }

    fn is_success(&self) -> bool {
        self.success
    }
}

impl SystemResult {
    /// Format system status for display
    fn format_system_status(&self) -> String {
        let mut output = String::new();

        output.push_str("=== System Status ===\n\n");

        if let Some(system) = self.data.get("system") {
            output.push_str("System:\n");
            if let Some(uptime) = system.get("uptime_seconds").and_then(|u| u.as_u64()) {
                let hours = uptime / 3600;
                let minutes = (uptime % 3600) / 60;
                output.push_str(&format!("  Uptime: {}h {}m\n", hours, minutes));
            }

            if let Some(memory) = system.get("memory_usage") {
                if let (Some(used), Some(total)) = (
                    memory.get("used_mb").and_then(|u| u.as_u64()),
                    memory.get("total_mb").and_then(|t| t.as_u64()),
                ) {
                    let usage_percent = (used as f64 / total as f64) * 100.0;
                    output.push_str(&format!(
                        "  Memory: {} MB / {} MB ({:.1}%)\n",
                        used, total, usage_percent
                    ));
                }
            }

            if let Some(cpu) = system.get("cpu_usage") {
                if let Some(usage) = cpu.get("usage_percent").and_then(|u| u.as_f64()) {
                    output.push_str(&format!("  CPU Usage: {:.1}%\n", usage));
                }
            }
        }

        output.push('\n');

        if let Some(cli) = self.data.get("semantic_cli") {
            output.push_str("Semantic CLI:\n");
            if let Some(version) = cli.get("version").and_then(|v| v.as_str()) {
                output.push_str(&format!("  Version: {}\n", version));
            }
            if let Some(phase) = cli.get("phase").and_then(|p| p.as_str()) {
                output.push_str(&format!("  Phase: {}\n", phase));
            }
            if let Some(gate) = cli.get("gate").and_then(|g| g.as_str()) {
                output.push_str(&format!("  Gate: {}\n", gate));
            }
            if let Some(status) = cli.get("status").and_then(|s| s.as_str()) {
                output.push_str(&format!("  Status: {}\n", status));
            }
        }

        output.push('\n');

        if let Some(context_mgr) = self.data.get("context_manager") {
            output.push_str("Context Manager:\n");
            if let Some(contexts) = context_mgr.get("contexts_loaded").and_then(|c| c.as_u64()) {
                output.push_str(&format!("  Contexts Loaded: {}\n", contexts));
            }
            if let Some(hit_rate) = context_mgr.get("cache_hit_rate").and_then(|h| h.as_f64()) {
                output.push_str(&format!("  Cache Hit Rate: {:.1}%\n", hit_rate * 100.0));
            }
        }

        output.push_str(&format!("\nExecution time: {}ms", self.execution_time_ms));

        output
    }

    /// Format agent list for display
    fn format_agent_list(&self) -> String {
        let mut output = String::new();

        output.push_str("=== Active Agents ===\n\n");

        if let Some(agents_data) = self.data.get("agents").and_then(|a| a.as_array()) {
            if agents_data.is_empty() {
                output.push_str("No agents currently active.\n");
            } else {
                for (index, agent) in agents_data.iter().enumerate() {
                    output.push_str(&format!("{}. {}\n", index + 1, self.format_agent(agent)));
                }
            }
        }

        if let Some(total) = self.data.get("total_count").and_then(|t| t.as_u64()) {
            if let Some(active) = self.data.get("active_count").and_then(|a| a.as_u64()) {
                output.push_str(&format!(
                    "\nSummary: {} active agents (of {} total)\n",
                    active, total
                ));
            }
        }

        output.push_str(&format!("Execution time: {}ms", self.execution_time_ms));

        output
    }

    /// Format individual agent for display
    fn format_agent(&self, agent: &JsonValue) -> String {
        if let Some(obj) = agent.as_object() {
            let id = obj.get("id").and_then(|i| i.as_str()).unwrap_or("unknown");
            let name = obj
                .get("name")
                .and_then(|n| n.as_str())
                .unwrap_or("unnamed");
            let status = obj
                .get("status")
                .and_then(|s| s.as_str())
                .unwrap_or("unknown");
            let agent_type = obj
                .get("type")
                .and_then(|t| t.as_str())
                .unwrap_or("unknown");

            format!("{} ({}) - {} [{}]", name, id, status, agent_type)
        } else {
            "Invalid agent data".to_string()
        }
    }

    /// Create error result
    pub fn error(operation_type: String, error_message: String, execution_time_ms: u64) -> Self {
        Self {
            operation_type,
            data: JsonValue::Null,
            execution_time_ms,
            success: false,
            error_message: Some(error_message),
        }
    }

    /// Create empty result
    pub fn empty(operation_type: String, execution_time_ms: u64) -> Self {
        Self {
            operation_type,
            data: json!({}),
            execution_time_ms,
            success: true,
            error_message: None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::bcib::{ContextInstruction, SystemInstruction};
    use crate::types::SourceLocation;

    fn create_status_bcib_sequence() -> Vec<BCIBInstruction> {
        vec![
            BCIBInstruction::System(SystemInstruction::SystemStatus {
                location: SourceLocation::default(),
            }),
            BCIBInstruction::Context(ContextInstruction::Return {
                location: SourceLocation::default(),
            }),
        ]
    }

    fn create_agents_bcib_sequence() -> Vec<BCIBInstruction> {
        vec![
            BCIBInstruction::System(SystemInstruction::ListAgents {
                location: SourceLocation::default(),
            }),
            BCIBInstruction::Context(ContextInstruction::Return {
                location: SourceLocation::default(),
            }),
        ]
    }

    #[test]
    fn test_system_executor_creation() {
        let executor = SystemExecutor::new();
        assert!(executor.context_manager().context_exists("system.agents"));
    }

    #[test]
    fn test_system_status_execution() {
        let mut executor = SystemExecutor::new();
        let input = SystemInput {
            instructions: create_status_bcib_sequence(),
        };

        let result = executor.execute_bcib_sequence(input);
        assert!(result.is_ok());

        let system_result = result.unwrap();
        assert!(system_result.is_success());
        assert_eq!(system_result.operation_type, "status");
        assert!(system_result.execution_time_ms < 50); // Performance target

        // Verify status data structure
        assert!(system_result.data.get("system").is_some());
        assert!(system_result.data.get("semantic_cli").is_some());
        assert!(system_result.data.get("context_manager").is_some());
    }

    #[test]
    fn test_agents_list_execution() {
        let mut executor = SystemExecutor::new();
        let input = SystemInput {
            instructions: create_agents_bcib_sequence(),
        };

        let result = executor.execute_bcib_sequence(input);
        assert!(result.is_ok());

        let system_result = result.unwrap();
        assert!(system_result.is_success());
        assert_eq!(system_result.operation_type, "agents");
        assert!(system_result.execution_time_ms < 100); // Performance target (relaxed for test environment)

        // Verify agents data structure
        assert!(system_result.data.get("agents").is_some());
        assert!(system_result.data.get("total_count").is_some());
        assert!(system_result.data.get("active_count").is_some());
    }

    #[test]
    fn test_empty_instructions() {
        let mut executor = SystemExecutor::new();
        let input = SystemInput {
            instructions: Vec::new(),
        };

        let result = executor.execute_bcib_sequence(input);
        assert!(result.is_err());
    }

    #[test]
    fn test_invalid_instruction_type() {
        let mut executor = SystemExecutor::new();
        let input = SystemInput {
            instructions: vec![BCIBInstruction::Query(
                crate::bcib::QueryInstruction::ApplyFilter {
                    expression: crate::bcib::FilterExpression::new(
                        "test".to_string(),
                        crate::bcib::ComparisonOp::Equal,
                        crate::bcib::OperandRef::Literal(crate::bcib::Value::String(
                            "test".to_string(),
                        )),
                    ),
                    location: SourceLocation::default(),
                },
            )],
        };

        let result = executor.execute_bcib_sequence(input);
        assert!(result.is_err());
    }

    #[test]
    fn test_system_status_formatting() {
        let result = SystemResult {
            operation_type: "status".to_string(),
            data: json!({
                "system": {
                    "uptime_seconds": 7200,
                    "memory_usage": {
                        "used_mb": 2048,
                        "total_mb": 8192
                    },
                    "cpu_usage": {
                        "usage_percent": 15.5
                    }
                },
                "semantic_cli": {
                    "version": "0.1.0",
                    "phase": "3.5.1.a",
                    "gate": "B",
                    "status": "operational"
                }
            }),
            execution_time_ms: 25,
            success: true,
            error_message: None,
        };

        let formatted = result.format();
        assert!(formatted.contains("=== System Status ==="));
        assert!(formatted.contains("Uptime: 2h 0m"));
        assert!(formatted.contains("Memory: 2048 MB / 8192 MB (25.0%)"));
        assert!(formatted.contains("CPU Usage: 15.5%"));
        assert!(formatted.contains("Version: 0.1.0"));
        assert!(formatted.contains("25ms"));
    }

    #[test]
    fn test_agents_list_formatting() {
        let result = SystemResult {
            operation_type: "agents".to_string(),
            data: json!({
                "agents": [
                    {
                        "id": "agent_001",
                        "name": "Query Agent",
                        "status": "active",
                        "type": "query"
                    },
                    {
                        "id": "agent_002",
                        "name": "System Agent",
                        "status": "active",
                        "type": "system"
                    }
                ],
                "total_count": 2,
                "active_count": 2
            }),
            execution_time_ms: 15,
            success: true,
            error_message: None,
        };

        let formatted = result.format();
        assert!(formatted.contains("=== Active Agents ==="));
        assert!(formatted.contains("Query Agent (agent_001) - active [query]"));
        assert!(formatted.contains("System Agent (agent_002) - active [system]"));
        assert!(formatted.contains("Summary: 2 active agents (of 2 total)"));
        assert!(formatted.contains("15ms"));
    }

    #[test]
    fn test_system_result_metadata() {
        let result = SystemResult {
            operation_type: "status".to_string(),
            data: json!({"test": "data"}),
            execution_time_ms: 30,
            success: true,
            error_message: None,
        };

        let metadata = result.metadata();
        assert_eq!(
            metadata.get("operation_type").unwrap().as_str().unwrap(),
            "status"
        );
        assert_eq!(
            metadata.get("execution_time_ms").unwrap().as_u64().unwrap(),
            30
        );
        assert_eq!(metadata.get("success").unwrap().as_bool().unwrap(), true);
    }

    #[test]
    fn test_error_result() {
        let result = SystemResult::error("status".to_string(), "Test error".to_string(), 5);

        assert!(!result.is_success());
        assert_eq!(result.error_message.as_ref().unwrap(), "Test error");
        assert!(result.format().contains("Error: Test error"));
    }

    #[test]
    fn test_empty_result() {
        let result = SystemResult::empty("status".to_string(), 10);

        assert!(result.is_success());
        assert_eq!(result.operation_type, "status");
        assert_eq!(result.execution_time_ms, 10);
    }

    #[test]
    fn test_performance_target() {
        let mut executor = SystemExecutor::new();
        let input = SystemInput {
            instructions: create_status_bcib_sequence(),
        };

        let start = Instant::now();
        let result = executor.execute_bcib_sequence(input);
        let duration = start.elapsed();

        assert!(result.is_ok());
        assert!(duration.as_millis() < 50); // Performance target: < 50ms

        let system_result = result.unwrap();
        assert!(system_result.execution_time_ms < 50);
    }

    #[test]
    fn test_multiple_system_operations_rejected() {
        let mut executor = SystemExecutor::new();
        let input = SystemInput {
            instructions: vec![
                BCIBInstruction::System(SystemInstruction::SystemStatus {
                    location: SourceLocation::default(),
                }),
                BCIBInstruction::System(SystemInstruction::ListAgents {
                    location: SourceLocation::default(),
                }),
                BCIBInstruction::Context(ContextInstruction::Return {
                    location: SourceLocation::default(),
                }),
            ],
        };

        let result = executor.execute_bcib_sequence(input);
        assert!(result.is_err());

        if let Err(error) = result {
            assert!(error.to_string().contains("Multiple system operations"));
        }
    }

    #[test]
    fn test_no_system_operation_rejected() {
        let mut executor = SystemExecutor::new();
        let input = SystemInput {
            instructions: vec![BCIBInstruction::Context(ContextInstruction::Return {
                location: SourceLocation::default(),
            })],
        };

        let result = executor.execute_bcib_sequence(input);
        assert!(result.is_err());

        if let Err(error) = result {
            assert!(error.to_string().contains("No system operation found"));
        }
    }
}
