#ifndef AYKEN_BOOT_FLAGS_H
#define AYKEN_BOOT_FLAGS_H

#include <stdint.h>

#define AYKEN_BOOT_ABI_VERSION 2u

#define AYKEN_BOOT_FLAG_PAGING_READY   (1u << 0)
#define AYKEN_BOOT_FLAG_FB_VALID       (1u << 1)
#define AYKEN_BOOT_FLAG_ACPI_PRESENT   (1u << 2)
#define AYKEN_BOOT_FLAG_SMP_AVAILABLE  (1u << 3)

#define AYKEN_BOOT_KNOWN_FLAGS ( \
    AYKEN_BOOT_FLAG_PAGING_READY | \
    AYKEN_BOOT_FLAG_FB_VALID     | \
    AYKEN_BOOT_FLAG_ACPI_PRESENT | \
    AYKEN_BOOT_FLAG_SMP_AVAILABLE )

#endif
