#!/usr/bin/env python3
"""Embed an ELF binary as a C array header."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate C header with embedded ELF bytes."
    )
    parser.add_argument("--input", default=None, help="Input ELF path (single-payload mode)")
    parser.add_argument("--output", required=True, help="Output header path")
    parser.add_argument(
        "--symbol",
        default="embedded_elf",
        help="Base symbol name (default: embedded_elf)",
    )
    parser.add_argument(
        "--mode",
        default="phase10a2",
        help="Payload mode string (default: phase10a2)",
    )
    parser.add_argument(
        "--bcib-input",
        default=None,
        help="BCIB worker ELF path (dual-payload mode)",
    )
    parser.add_argument(
        "--user-input",
        default=None,
        help="USER worker ELF path (dual-payload mode)",
    )
    return parser.parse_args()


def make_guard(path: Path) -> str:
    stem = path.name.upper().replace(".", "_")
    return f"AYKEN_{stem}"


def format_array(data: bytes) -> str:
    if not data:
        return ""
    lines: list[str] = []
    for i in range(0, len(data), 12):
        chunk = data[i : i + 12]
        line = ", ".join(f"0x{byte:02x}" for byte in chunk)
        lines.append(f"    {line},")
    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    guard = make_guard(output_path)

    # Check if dual-payload mode
    if args.bcib_input and args.user_input:
        # Dual-payload mode
        bcib_path = Path(args.bcib_input)
        user_path = Path(args.user_input)
        
        if not bcib_path.is_file():
            raise SystemExit(f"missing BCIB worker ELF: {bcib_path}")
        if not user_path.is_file():
            raise SystemExit(f"missing USER worker ELF: {user_path}")
        
        bcib_blob = bcib_path.read_bytes()
        user_blob = user_path.read_bytes()
        bcib_sha256 = hashlib.sha256(bcib_blob).hexdigest()
        user_sha256 = hashlib.sha256(user_blob).hexdigest()
        
        header = (
            f"/* Auto-generated by tools/embed_elf.py (dual-payload mode) */\n"
            f"#ifndef {guard}\n"
            f"#define {guard}\n\n"
            f"#include <stddef.h>\n"
            f"#include <stdint.h>\n\n"
            f"#define AYKEN_EMBEDDED_ELF_DUAL_PAYLOAD 1\n\n"
            f"/* BCIB Worker Payload */\n"
            f"static const uint8_t embedded_elf_bcib[] = {{\n"
            f"{format_array(bcib_blob)}}};\n\n"
            f"static const size_t embedded_elf_bcib_size = sizeof(embedded_elf_bcib);\n\n"
            f"static const char embedded_elf_bcib_sha256[] = \"{bcib_sha256}\";\n\n"
            f"/* USER Worker Payload */\n"
            f"static const uint8_t embedded_elf_user[] = {{\n"
            f"{format_array(user_blob)}}};\n\n"
            f"static const size_t embedded_elf_user_size = sizeof(embedded_elf_user);\n\n"
            f"static const char embedded_elf_user_sha256[] = \"{user_sha256}\";\n\n"
            f"/* Legacy compatibility (points to BCIB worker) */\n"
            f"static const uint8_t *embedded_elf = embedded_elf_bcib;\n"
            f"static const size_t embedded_elf_size = sizeof(embedded_elf_bcib);\n"
            f"static const char *embedded_elf_sha256 = embedded_elf_bcib_sha256;\n"
            f"static const char embedded_elf_mode[] = \"dual-worker-pipeline\";\n\n"
            f"static inline int verify_embedded_elf_hash(const char *expected) {{\n"
            f"    if (!expected) return -1;\n"
            f"    const char *a = embedded_elf_sha256;\n"
            f"    const char *b = expected;\n"
            f"    while (*a && *b) {{\n"
            f"        if (*a != *b) return -1;\n"
            f"        a++; b++;\n"
            f"    }}\n"
            f"    return (*a == *b) ? 0 : -1;\n"
            f"}}\n\n"
            f"#endif /* {guard} */\n"
        )
    else:
        # Single-payload mode (legacy)
        if not args.input:
            raise SystemExit("Error: --input required for single-payload mode")
        
        input_path = Path(args.input)
        symbol = args.symbol
        mode = args.mode

        if not input_path.is_file():
            raise SystemExit(f"missing input ELF: {input_path}")

        blob = input_path.read_bytes()
        blob_sha256 = hashlib.sha256(blob).hexdigest()

        header = (
            f"/* Auto-generated by tools/embed_elf.py from {input_path} */\n"
            f"#ifndef {guard}\n"
            f"#define {guard}\n\n"
            f"#include <stddef.h>\n"
            f"#include <stdint.h>\n\n"
            f"#define AYKEN_EMBEDDED_ELF_DUAL_PAYLOAD 0\n\n"
            f"static const uint8_t {symbol}[] = {{\n"
            f"{format_array(blob)}}};\n\n"
            f"static const size_t {symbol}_size = sizeof({symbol});\n\n"
            f"static const char {symbol}_sha256[] = \"{blob_sha256}\";\n\n"
            f"static const char {symbol}_mode[] = \"{mode}\";\n\n"
            f"static inline int verify_{symbol}_hash(const char *expected) {{\n"
            f"    if (!expected) return -1;\n"
            f"    const char *a = {symbol}_sha256;\n"
            f"    const char *b = expected;\n"
            f"    while (*a && *b) {{\n"
            f"        if (*a != *b) return -1;\n"
            f"        a++; b++;\n"
            f"    }}\n"
            f"    return (*a == *b) ? 0 : -1;\n"
            f"}}\n\n"
            f"#endif /* {guard} */\n"
        )

    # Keep workspace deterministic: avoid rewriting file when content is unchanged.
    if output_path.exists():
        current = output_path.read_text(encoding="utf-8")
        if current == header:
            return 0

    output_path.write_text(header, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
