#!/usr/bin/env python3
"""Embed an ELF binary as a C array header."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate C header with embedded ELF bytes."
    )
    parser.add_argument("--input", required=True, help="Input ELF path")
    parser.add_argument("--output", required=True, help="Output header path")
    parser.add_argument(
        "--symbol",
        default="embedded_elf",
        help="Base symbol name (default: embedded_elf)",
    )
    return parser.parse_args()


def make_guard(path: Path) -> str:
    stem = path.name.upper().replace(".", "_")
    return f"AYKEN_{stem}"


def format_array(data: bytes) -> str:
    if not data:
        return ""
    lines: list[str] = []
    for i in range(0, len(data), 12):
        chunk = data[i : i + 12]
        line = ", ".join(f"0x{byte:02x}" for byte in chunk)
        lines.append(f"    {line},")
    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    input_path = Path(args.input)
    output_path = Path(args.output)
    symbol = args.symbol

    if not input_path.is_file():
        raise SystemExit(f"missing input ELF: {input_path}")

    blob = input_path.read_bytes()
    blob_sha256 = hashlib.sha256(blob).hexdigest()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    guard = make_guard(output_path)

    header = (
        f"/* Auto-generated by tools/embed_elf.py from {input_path} */\n"
        f"#ifndef {guard}\n"
        f"#define {guard}\n\n"
        f"#include <stddef.h>\n"
        f"#include <stdint.h>\n\n"
        f"static const uint8_t {symbol}[] = {{\n"
        f"{format_array(blob)}}};\n\n"
        f"static const size_t {symbol}_size = sizeof({symbol});\n\n"
        f"static const char {symbol}_sha256[] = \"{blob_sha256}\";\n\n"
        f"#endif /* {guard} */\n"
    )

    # Keep workspace deterministic: avoid rewriting file when content is unchanged.
    if output_path.exists():
        current = output_path.read_text(encoding="utf-8")
        if current == header:
            return 0

    output_path.write_text(header, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
