// kernel/proc/bcib_worker.c
// ============================================================================
// Phase-16 Task 5: BCIB Worker Infrastructure
// 
// BCIB Role Provisioning - Kernel-Created BCIB Worker Context
// 
// Purpose:
//   Create a dedicated kernel-managed BCIB worker process for validation
//   testing. This enables end-to-end execution pipeline testing while
//   maintaining strict USER/BCIB role separation.
//
// Constitutional Compliance:
//   - SECURITY.BOUNDARY.VIOLATION: Role enforcement is NON_OVERRIDABLE
//   - KERNEL.SAFETY.CRITICAL: Role assignment is kernel-authoritative
//   - No backdoors, no role escalation, no enforcement bypass
//
// Validation Profile Only:
//   BCIB worker creation is ONLY enabled in validation profile builds.
//   Production builds do not include this infrastructure.
// ============================================================================

#include "../include/proc.h"
#include "../include/mm.h"
#include "../include/serial.h"
#include "../include/embedded_elf.h"
#include "../arch/x86_64/port_io.h"
#include <stddef.h>

// Validation profile guard
#if defined(AYKEN_VALIDATION) && (AYKEN_VALIDATION == 1)

// BCIB worker state (validation profile only)
static proc_t *g_bcib_worker = NULL;
static uint64_t g_bcib_worker_pid = 0;

// USER worker state (validation profile only)
static proc_t *g_user_worker = NULL;
static uint64_t g_user_worker_pid = 0;

// BCIB worker entry point (external assembly)
extern void bcib_worker_entry(void);

// Dual-channel debug output
static void bcib_debug(const char *msg) {
    if (!msg) return;
    while (*msg) {
        outb(0xE9, (uint8_t)*msg);
        outb(0x3F8, (uint8_t)*msg);
        msg++;
    }
}

/**
 * bcib_worker_create - Create BCIB worker process (validation profile only)
 * 
 * Creates a dedicated BCIB-role process during kernel initialization.
 * This worker can call SYS_V2_SUBMIT_EXECUTION without enforcement violation.
 * 
 * Acceptance Criteria:
 *   - Worker process created with deterministic PID
 *   - Process has PROC_EXECUTION_ROLE_BCIB from creation
 *   - Worker has inbox/payload regions mapped
 *   - Worker can call SYS_V2_SUBMIT_EXECUTION without kill
 * 
 * Returns:
 *   0 on success, -1 on failure
 */
int bcib_worker_create(void) {
    bcib_debug("[[AYKEN_BCIB_WORKER_CREATE_BEGIN]]\n");
    
    // Guard: Only create once
    if (g_bcib_worker != NULL) {
        bcib_debug("[[AYKEN_BCIB_WORKER_CREATE_SKIP]] already_created\n");
        return 0;
    }
    
    // Create BCIB worker process with actual BCIB worker payload
    // In dual-payload mode, use embedded_elf_bcib; otherwise use embedded_elf (legacy)
    // Symbols are generated by tools/embed_elf.py and defined in kernel/include/embedded_elf.h
#ifdef embedded_elf_bcib
    const uint8_t *image = embedded_elf_bcib;
    uint64_t image_size = (uint64_t)embedded_elf_bcib_size;
#else
    const uint8_t *image = embedded_elf;
    uint64_t image_size = (uint64_t)embedded_elf_size;
#endif
    
    // Create user process with BCIB worker name
    proc_t *worker = proc_create_user_process("bcib_worker", image, image_size, PROC_IMAGE_ELF);
    
    if (worker == NULL) {
        bcib_debug("[[AYKEN_BCIB_WORKER_CREATE_FAIL]] proc_create_failed\n");
        return -1;
    }
    
    // CRITICAL: Assign BCIB execution role
    // This is the kernel-authoritative role assignment that enables
    // the worker to call SYS_V2_SUBMIT_EXECUTION without enforcement violation
    worker->execution_role = PROC_EXECUTION_ROLE_BCIB;
    
    // Store worker reference
    g_bcib_worker = worker;
    g_bcib_worker_pid = (uint64_t)worker->pid;
    
    // Emit success marker with PID and role
    bcib_debug("[[AYKEN_BCIB_WORKER_CREATE_OK]] pid=");
    
    // Emit PID as decimal digits
    uint64_t pid = g_bcib_worker_pid;
    if (pid == 0) {
        outb(0xE9, '0');
        outb(0x3F8, '0');
    } else {
        char digits[20];
        int i = 0;
        while (pid > 0) {
            digits[i++] = '0' + (pid % 10);
            pid /= 10;
        }
        // Reverse digits
        for (int j = i - 1; j >= 0; j--) {
            outb(0xE9, (uint8_t)digits[j]);
            outb(0x3F8, (uint8_t)digits[j]);
        }
    }
    
    bcib_debug(" role=BCIB\n");
    
    return 0;
}

/**
 * bcib_worker_get_pid - Get BCIB worker PID
 * 
 * Returns the PID of the BCIB worker process for test coordination.
 * 
 * Returns:
 *   Worker PID, or 0 if worker not created
 */
uint64_t bcib_worker_get_pid(void) {
    return g_bcib_worker_pid;
}

/**
 * bcib_worker_get_proc - Get BCIB worker process structure
 * 
 * Returns the process structure for the BCIB worker.
 * Used for test coordination and validation.
 * 
 * Returns:
 *   Worker process pointer, or NULL if worker not created
 */
proc_t *bcib_worker_get_proc(void) {
    return g_bcib_worker;
}

/**
 * user_worker_create - Create USER worker process (validation profile only)
 * 
 * Creates a dedicated USER-role process during kernel initialization.
 * This worker can poll execution inbox and complete executions.
 * 
 * Acceptance Criteria:
 *   - Worker process created with deterministic PID
 *   - Process has PROC_EXECUTION_ROLE_USER from creation
 *   - Worker has inbox/payload regions mapped
 *   - Worker can call SYS_V2_COMPLETE_EXECUTION without kill
 * 
 * Returns:
 *   0 on success, -1 on failure
 */
int user_worker_create(void) {
    bcib_debug("[[AYKEN_USER_WORKER_CREATE_BEGIN]]\n");
    
    // Guard: Only create once
    if (g_user_worker != NULL) {
        bcib_debug("[[AYKEN_USER_WORKER_CREATE_SKIP]] already_created\n");
        return 0;
    }
    
    // Create USER worker process with actual USER worker payload
    // In dual-payload mode, use embedded_elf_user; otherwise use embedded_elf (legacy)
    // Symbols are generated by tools/embed_elf.py and defined in kernel/include/embedded_elf.h
#ifdef embedded_elf_user
    const uint8_t *image = embedded_elf_user;
    uint64_t image_size = (uint64_t)embedded_elf_user_size;
#else
    // TEMPORARY: Use same embedded_elf for now (legacy single-payload mode)
    const uint8_t *image = embedded_elf;
    uint64_t image_size = (uint64_t)embedded_elf_size;
#endif
    
    // Create user process with USER worker name
    proc_t *worker = proc_create_user_process("user_worker", image, image_size, PROC_IMAGE_ELF);
    
    if (worker == NULL) {
        bcib_debug("[[AYKEN_USER_WORKER_CREATE_FAIL]] proc_create_failed\n");
        return -1;
    }
    
    // CRITICAL: Assign USER execution role (default, but explicit for clarity)
    // USER role allows SYS_V2_COMPLETE_EXECUTION but NOT SYS_V2_SUBMIT_EXECUTION
    worker->execution_role = PROC_EXECUTION_ROLE_USER;
    
    // Store worker reference
    g_user_worker = worker;
    g_user_worker_pid = (uint64_t)worker->pid;
    
    // Emit success marker with PID and role
    bcib_debug("[[AYKEN_USER_WORKER_CREATE_OK]] pid=");
    
    // Emit PID as decimal digits
    uint64_t pid = g_user_worker_pid;
    if (pid == 0) {
        outb(0xE9, '0');
        outb(0x3F8, '0');
    } else {
        char digits[20];
        int i = 0;
        while (pid > 0) {
            digits[i++] = '0' + (pid % 10);
            pid /= 10;
        }
        // Reverse digits
        for (int j = i - 1; j >= 0; j--) {
            outb(0xE9, (uint8_t)digits[j]);
            outb(0x3F8, (uint8_t)digits[j]);
        }
    }
    
    bcib_debug(" role=USER\n");
    
    return 0;
}

/**
 * user_worker_get_pid - Get USER worker PID
 * 
 * Returns the PID of the USER worker process for test coordination.
 * 
 * Returns:
 *   Worker PID, or 0 if worker not created
 */
uint64_t user_worker_get_pid(void) {
    return g_user_worker_pid;
}

/**
 * user_worker_get_proc - Get USER worker process structure
 * 
 * Returns the process structure for the USER worker.
 * Used for test coordination and validation.
 * 
 * Returns:
 *   Worker process pointer, or NULL if worker not created
 */
proc_t *user_worker_get_proc(void) {
    return g_user_worker;
}

#else // !AYKEN_VALIDATION

// Production builds: BCIB worker infrastructure not available
int bcib_worker_create(void) {
    return -1;  // Not available in production
}

uint64_t bcib_worker_get_pid(void) {
    return 0;  // Not available in production
}

proc_t *bcib_worker_get_proc(void) {
    return NULL;  // Not available in production
}

int user_worker_create(void) {
    return -1;  // Not available in production
}

uint64_t user_worker_get_pid(void) {
    return 0;  // Not available in production
}

proc_t *user_worker_get_proc(void) {
    return NULL;  // Not available in production
}

#endif // AYKEN_VALIDATION

